book_demo/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('books.urls')),
]

books/urls.py
from django.urls import path

from . import views

app_name = 'books'

urlpatterns = [
    path('', views.ManageView.as_view(), name='manage'),
    path('add/', views.AddBookView.as_view(), name='add'),
    path('edit/<int:pk>', views.EditBookView.as_view(), name='edit'),
    path('delete/<int:pk>', views.deleteBook, name='delete'),
]

books/models.py
from unicodedata import name
from django.db import models
from django.urls import reverse

# Create your models here.


class Category(models.Model):
    name = models.CharField(max_length=255)

    def __str__(self):
        return self.name


class Author(models.Model):
    name = models.CharField(max_length=255)
    biography = models.TextField()

    def __str__(self):
        return self.name


class Publisher(models.Model):
    name = models.CharField(max_length=255)
    address = models.CharField(max_length=255)

    def __str__(self):
        return self.name


class Book(models.Model):
    title = models.CharField(max_length=255)
    category = models.ForeignKey(Category, on_delete=models.RESTRICT)
    publisher = models.ForeignKey(Publisher, on_delete=models.RESTRICT)
    authors = models.ManyToManyField(Author)
    pages = models.IntegerField()
    language = models.CharField(max_length=255)
    summary = models.TextField()

    def __str__(self):
        return self.title

    def get_absolute_url(self):
        return reverse("books:manage")

books/forms.py
from django import forms
from .models import Book

class BookForm(forms.ModelForm):
    class Meta:
        model = Book
        fields = ['title','category','publisher','authors','pages','language','summary']
        widgets = {
            'title':forms.TextInput(attrs={'class':'form-control'}),
            'category':forms.Select(attrs={'class':'form-control'}),
            'publisher':forms.Select(attrs={'class':'form-control'}),
            'authors':forms.SelectMultiple(attrs={'class':'form-control'}),
            'pages':forms.NumberInput(attrs={'class':'form-control'}),
            'language':forms.TextInput(attrs={'class':'form-control'}),
            'summary':forms.Textarea(attrs={'class':'form-control'}),
        }
    
    def __init__(self, *args, **kargs):
            super().__init__(*args, **kargs)
            self.fields['category'].empty_label = None
            self.fields['publisher'].empty_label = None
            self.fields['authors'].empty_label = None
            # self.fields['publisher'].queryset = Publisher.objects.filter(status=True)
    

books/views.py
from pyexpat import model
from django.shortcuts import render, redirect
from django.http import HttpResponse
from .forms import BookForm
from .models import Book
from django.views.generic import ListView, CreateView, UpdateView, DetailView

# Create your views here.

class ManageView(ListView):
    context_object_name = 'books'
    queryset = Book.objects.all()
    template_name = 'books/index.html'

class AddBookView(CreateView):
    form_class = BookForm
    template_name = 'books/add_edit.html'

class EditBookView(UpdateView):
    model = Book
    form_class = BookForm
    template_name = 'books/add_edit.html'

def deleteBook(request,pk):
    Book.objects.get(id=pk).delete()
    return redirect('books:manage')

books/templates/books/add_edit.html
{% extends 'books/base.html' %}
{% block content %}
<div class="form-group">
    <form method="POST">
        {% csrf_token %}
        {{form.as_p}}
        <button type="submit" class="btn btn-success">
            <i class="fas fa-download"></i> Save
        </button>
    </form>
</div>
{% endblock %}

books/templates/books/base.html
<!DOCTYPE html>
<html>

<head>
    <meta charset="UTF-8">
    <meta name="description" content="ban laptop uy tin, chat luong, dich vu tot">
    <meta name="keywords" content="laptop, asus, dell, hp, lenovo, acer, apple, msi, lg">
    <meta name="author" content="CuongPham">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">

    {% load static %}

    <!-- CSS -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css">
    <link rel="stylesheet" type="text/css" href="{% static 'books/css/fontawesome.min.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'books/css/style.css' %}">


    <!-- JavaScript -->
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.16.0/umd/popper.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js"></script>
    <script src="{% static 'books/js/fontawesome.min.js' %}"></script>
    <script src="{% static 'books/js/manage_book.js' %}"></script>

    <title>Book Store Online</title>
</head>

<body>
    <!-- MAIN -->
    <div id="main">
        <div class="sidebar">
            <div class="sidebar-inner">
                <div class="sidebar-logo">
                    <a class="sidebar-link" href="{% url 'books:manage' %}"> <img class="icon"
                            src="{% static 'books/img/logo.png' %}">
                        <h5 class="logo-text">Admin Manage</h5>
                    </a>
                </div>

                <nav class="navbar scrollbar" id="style-1">
                    <ul class="navbar-nav">
                        <li class="nav-item"><a class="nav-link" href="/BookStoreOnline/admin"><i
                                    class="fas fa-home"></i>Dashboard</a></li>
                        <li class="nav-item"><a class="nav-link" href="/BookStoreOnline/admin/manage/author"><i
                                    class="fas fa-pencil-alt"></i>Manage author</a></li>
                        <li class="nav-item"><a class="nav-link" href="/BookStoreOnline/admin/manage/publisher"><i
                                    class="fas fa-warehouse"></i>Manage publisher</a></li>
                        <li class="nav-item"><a class="nav-link" href="/BookStoreOnline/admin/manage/book"><i
                                    class="fas fa-book-open"></i>Manage book</a></li>
                        <li class="nav-item"><a class="nav-link" href="/BookStoreOnline/admin/manage/book-item"><i
                                    class="fas fa-book-reader"></i>Manage book item</a></li>
                        <li class="nav-item"><a class="nav-link" href="/BookStoreOnline/admin/manage/customer"><i
                                    class="fas fa-users"></i>Manage customer</a></li>
                        <li class="nav-item"><a class="nav-link" href="/BookStoreOnline/admin/manage/staff"><i
                                    class="fas fa-user-tie"></i>Manage staff</a></li>
                        <li class="nav-item"><a class="nav-link" href="/BookStoreOnline/admin/manage/order"><i
                                    class="fas fa-shopping-cart"></i>Manage order</a></li>
                        <li class="nav-item"><a class="nav-link" href="/BookStoreOnline/admin/manage/shipment"><i
                                    class="fas fa-shipping-fast"></i>Manage shipment</a></li>
                        <li class="nav-item dropdown"><a class="nav-link dropdown-toggle" href="#" id="navbardrop"
                                data-toggle="dropdown"><i class="fas fa-chart-bar"></i>Statistics</a>
                            <div class="dropdown-menu">
                                <a class="dropdown-item" href="/BookStoreOnline/admin/statistic/book-item">Thống kê
                                    top 9 quyển sách<br>được bán chạy nhất
                                </a> <a class="dropdown-item" href="/BookStoreOnline/admin/statistic/customer">Thống kê
                                    top
                                    9 khách hàng<br>chi mua nhiều nhất
                                </a> <a class="dropdown-item" href="/BookStoreOnline/admin/statistic/shipment">Thống kê
                                    top
                                    shipment<br>được sửa dụng nhiều nhất
                                </a> <a class="dropdown-item" href="/BookStoreOnline/admin/statistic/income">Thống kê
                                    thu nhập theo<br>một tháng của năm nào đó
                                </a>
                            </div>
                        </li>
                    </ul>

                </nav>
            </div>
        </div>
        <div class="page-container">
            <div class="header-container">
                <nav class="navbar">
                    <ul class="navbar-nav">
                        <li class="nav-item dropdown"><a class="nav-link dropdown-toggle" href="#" id="navbardrop"
                                data-toggle="dropdown"><img class="icon" alt="user"
                                    src="{% static 'books/img/icons8-user-male-100.png' %}">
                                <div class="text-icon">admin</div>
                            </a>
                            <div class="dropdown-menu">
                                <a class="dropdown-item" href="/BookStoreOnline/admin/view-profile-staff"><i
                                        class="far fa-user"></i>Profile</a> <a class="dropdown-item"
                                    href="/BookStoreOnline/logout-staff"><i class="fas fa-power-off"></i>Logout</a>
                            </div>
                        </li>
                    </ul>
                </nav>
            </div>

            <div class="main-content">
                <div class="row">
                    <div class="col-md-12">
                        <div class="form-add"> 
                            {% block content %}
                            {% endblock %}
                            
                        </div>
                    </div>
                </div>
            </div>
            <div class="footer">
                ©
                <c:set var="now" value="<%=new java.util.Date()%>" />
                <fmt:formatDate pattern="yyyy" value="${now}" />
                Copyright: <a href="https://www.facebook.com/cuongphamptit999/">
                    CuongPham.com</a>
            </div>
        </div>
    </div>

</body>

</html>

books/templates/books/index.html
{% extends 'books/base.html' %}
{% block content %}
<a href="{% url 'books:add' %}" class="btn btn-success" style="margin-top: 10px"><i class="fas fa-plus-square"></i>
    Add</a>

<h1 class="my-3"></h1>

<table class="table">
    <thead class="thead-light">
        <tr>
            <th>#</th>
            <th style="width: 230px;">Title</th>
            <th style="width: 230px;">Category</th>
            <th>Publisher</th>
            <th style="width: 230px;">Author</th>
            <th>Language</th>
            <th></th>
        </tr>
    </thead>
    <tbody id="myTable">
        {% for book in books %}
        <tr>
            <td>{{forloop.counter}}</td>
            <td>{{book.title }}</td>
            <td>{{book.category.name }}</td>
            <td>{{book.publisher.name }}</td>
            <td>
                {{book.authors.all|join:", " }}</td>
            <td>{{book.language }}</td>
            <td><a href="{% url 'books:edit' book.pk %}" class="btn btn-primary"><i class="fas fa-edit"></i> Edit</a>
                <a href="javascript:void(0);" onclick="Shop.delete('{% url 'books:delete' book.pk %}')"
                    class="btn btn-danger"><i class="fas fa-eraser"></i>
                    Delete</a>
            </td>
        </tr>
        {% endfor %}
    </tbody>
</table>
{% endblock %}